name: Publish to TestPyPi

on:
  workflow_dispatch:
    inputs:
      from_tag:
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - if: github.event_name != 'workflow_dispatch'
      uses: actions/checkout@v3
    - if: github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v3
      with:
        ref: refs/tags/${{ inputs.from_tag }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
          python -m build .

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          repository-url: https://test.pypi.org/legacy/
